image: cypress/included:13.6.4  # Includes Cypress v13.6.4 + Node 18 + Chrome/Firefox

pipelines:
  default:
    - step:
        name: Run Cypress Tests
        caches:
          - node
        script:
          - npm ci
          - npx cypress run --browser chrome
        artifacts:
          - cypress/results/**
          - cypress/videos/**
          - cypress/screenshots/**